// Demo data to showcase the GearGuard system
export const initializeDemoData = () => {
  const demoData = {
    teams: [
      { id: 1, name: 'Mechanics', specialization: 'Mechanical Equipment' },
      { id: 2, name: 'Electricians', specialization: 'Electrical Systems' },
      { id: 3, name: 'IT Support', specialization: 'Computer Equipment' }
    ],
    technicians: [
      { id: 1, name: 'Rajesh Kumar', teamId: 1, avatar: '👨‍🔧', activeRequests: 2 },
      { id: 2, name: 'Priya Sharma', teamId: 1, avatar: '👩‍🔧', activeRequests: 1 },
      { id: 3, name: 'Ahmed Hassan', teamId: 2, avatar: '👨‍💼', activeRequests: 3 },
      { id: 4, name: 'Maria Rodriguez', teamId: 2, avatar: '👩‍💼', activeRequests: 0 },
      { id: 5, name: 'Chen Wei', teamId: 3, avatar: '👨‍💻', activeRequests: 1 },
      { id: 6, name: 'Fatima Al-Zahra', teamId: 3, avatar: '👩‍💻', activeRequests: 2 },
      { id: 7, name: 'Arjun Patel', teamId: 1, avatar: '👨‍🔧', activeRequests: 0 },
      { id: 8, name: 'Aisha Johnson', teamId: 2, avatar: '👩‍💼', activeRequests: 1 },
      { id: 9, name: 'Carlos Santos', teamId: 3, avatar: '👨‍💻', activeRequests: 2 },
      { id: 10, name: 'Yuki Tanaka', teamId: 1, avatar: '👩‍🔧', activeRequests: 1 },
      { id: 11, name: 'Omar Ibrahim', teamId: 2, avatar: '👨‍💼', activeRequests: 0 },
      { id: 12, name: 'Sophie Dubois', teamId: 3, avatar: '👩‍💻', activeRequests: 3 },
      { id: 13, name: 'Kwame Asante', teamId: 1, avatar: '👨‍🔧', activeRequests: 1 },
      { id: 14, name: 'Elena Petrov', teamId: 2, avatar: '👩‍💼', activeRequests: 2 },
      { id: 15, name: 'Hiroshi Yamamoto', teamId: 3, avatar: '👨‍💻', activeRequests: 0 },
      { id: 16, name: 'Amara Okafor', teamId: 1, avatar: '👩‍🔧', activeRequests: 1 },
      { id: 17, name: 'Diego Fernandez', teamId: 2, avatar: '👨‍💼', activeRequests: 2 },
      { id: 18, name: 'Zara Al-Rashid', teamId: 3, avatar: '👩‍💻', activeRequests: 1 }
    ],
    equipment: [
      {
        id: 1,
        name: 'CNC Machine #1',
        serialNumber: 'CNC-001',
        purchaseDate: '2022-01-15',
        warrantyExpiry: '2025-01-15',
        location: 'Factory Floor A',
        department: 'Production',
        assignedTeamId: 1,
        healthScore: 85,
        isUsable: true
      },
      {
        id: 2,
        name: 'Server Rack #1',
        serialNumber: 'SRV-001',
        purchaseDate: '2023-03-10',
        warrantyExpiry: '2026-03-10',
        location: 'Data Center',
        department: 'IT',
        assignedTeamId: 3,
        healthScore: 95,
        isUsable: true
      },
      {
        id: 3,
        name: 'Hydraulic Press #2',
        serialNumber: 'HYD-002',
        purchaseDate: '2021-06-20',
        warrantyExpiry: '2024-06-20',
        location: 'Factory Floor B',
        department: 'Production',
        assignedTeamId: 1,
        healthScore: 35,
        isUsable: true
      },
      {
        id: 4,
        name: 'Generator #1',
        serialNumber: 'GEN-001',
        purchaseDate: '2020-09-15',
        warrantyExpiry: '2023-09-15',
        location: 'Power Room',
        department: 'Facilities',
        assignedTeamId: 2,
        healthScore: 60,
        isUsable: true
      },
      {
        id: 5,
        name: 'Workstation PC #15',
        serialNumber: 'PC-015',
        purchaseDate: '2023-08-01',
        warrantyExpiry: '2026-08-01',
        location: 'Office Floor 2',
        department: 'Engineering',
        assignedTeamId: 3,
        healthScore: 100,
        isUsable: true
      },
      {
        id: 6,
        name: 'Conveyor Belt System #3',
        serialNumber: 'CVB-003',
        purchaseDate: '2022-11-05',
        warrantyExpiry: '2025-11-05',
        location: 'Assembly Line C',
        department: 'Production',
        assignedTeamId: 1,
        healthScore: 78,
        isUsable: true
      },
      {
        id: 7,
        name: 'Industrial Chiller #2',
        serialNumber: 'ICH-002',
        purchaseDate: '2021-04-12',
        warrantyExpiry: '2024-04-12',
        location: 'HVAC Room',
        department: 'Facilities',
        assignedTeamId: 2,
        healthScore: 42,
        isUsable: true
      },
      {
        id: 8,
        name: 'Network Switch #7',
        serialNumber: 'NSW-007',
        purchaseDate: '2023-02-28',
        warrantyExpiry: '2026-02-28',
        location: 'Server Room B',
        department: 'IT',
        assignedTeamId: 3,
        healthScore: 92,
        isUsable: true
      },
      {
        id: 9,
        name: 'Welding Robot #4',
        serialNumber: 'WRB-004',
        purchaseDate: '2022-07-18',
        warrantyExpiry: '2025-07-18',
        location: 'Welding Bay 2',
        department: 'Production',
        assignedTeamId: 1,
        healthScore: 67,
        isUsable: true
      },
      {
        id: 10,
        name: 'UPS System #1',
        serialNumber: 'UPS-001',
        purchaseDate: '2020-12-03',
        warrantyExpiry: '2023-12-03',
        location: 'Power Distribution',
        department: 'Facilities',
        assignedTeamId: 2,
        healthScore: 28,
        isUsable: true
      },
      {
        id: 11,
        name: 'Injection Molding Machine #5',
        serialNumber: 'IMM-005',
        purchaseDate: '2021-09-22',
        warrantyExpiry: '2024-09-22',
        location: 'Molding Department',
        department: 'Production',
        assignedTeamId: 1,
        healthScore: 73,
        isUsable: true
      },
      {
        id: 12,
        name: 'Air Compressor #3',
        serialNumber: 'ACM-003',
        purchaseDate: '2020-05-14',
        warrantyExpiry: '2023-05-14',
        location: 'Utility Room',
        department: 'Facilities',
        assignedTeamId: 2,
        healthScore: 55,
        isUsable: true
      },
      {
        id: 13,
        name: 'Database Server #2',
        serialNumber: 'DBS-002',
        purchaseDate: '2023-01-08',
        warrantyExpiry: '2026-01-08',
        location: 'Data Center',
        department: 'IT',
        assignedTeamId: 3,
        healthScore: 98,
        isUsable: true
      },
      {
        id: 14,
        name: 'Forklift #7',
        serialNumber: 'FLT-007',
        purchaseDate: '2022-03-25',
        warrantyExpiry: '2025-03-25',
        location: 'Warehouse A',
        department: 'Logistics',
        assignedTeamId: 1,
        healthScore: 82,
        isUsable: true
      },
      {
        id: 15,
        name: 'Transformer #2',
        serialNumber: 'TRF-002',
        purchaseDate: '2019-11-30',
        warrantyExpiry: '2022-11-30',
        location: 'Electrical Substation',
        department: 'Facilities',
        assignedTeamId: 2,
        healthScore: 45,
        isUsable: true
      },
      {
        id: 16,
        name: 'Firewall Server #1',
        serialNumber: 'FWS-001',
        purchaseDate: '2023-06-12',
        warrantyExpiry: '2026-06-12',
        location: 'Security Operations Center',
        department: 'IT',
        assignedTeamId: 3,
        healthScore: 100,
        isUsable: true
      },
      {
        id: 17,
        name: 'Packaging Machine #4',
        serialNumber: 'PKM-004',
        purchaseDate: '2021-12-18',
        warrantyExpiry: '2024-12-18',
        location: 'Packaging Line 2',
        department: 'Production',
        assignedTeamId: 1,
        healthScore: 69,
        isUsable: true
      },
      {
        id: 18,
        name: 'HVAC Unit #5',
        serialNumber: 'HVC-005',
        purchaseDate: '2020-08-07',
        warrantyExpiry: '2023-08-07',
        location: 'Building B - Roof',
        department: 'Facilities',
        assignedTeamId: 2,
        healthScore: 38,
        isUsable: true
      }
    ],
    requests: [
      {
        id: 1,
        subject: 'CNC Machine calibration needed',
        equipmentId: 1,
        type: 'Corrective',
        scheduledDate: '2024-12-28',
        duration: 3,
        assignedTechnicianId: 1,
        priority: 'Medium',
        status: 'New',
        createdAt: '2024-12-27T10:00:00Z'
      },
      {
        id: 2,
        subject: 'Monthly server maintenance',
        equipmentId: 2,
        type: 'Preventive',
        scheduledDate: '2024-12-30',
        duration: 2,
        assignedTechnicianId: 5,
        priority: 'Low',
        status: 'In Progress',
        createdAt: '2024-12-26T14:30:00Z'
      },
      {
        id: 3,
        subject: 'Hydraulic system leak repair',
        equipmentId: 3,
        type: 'Corrective',
        scheduledDate: '2024-12-27',
        duration: 4,
        assignedTechnicianId: 2,
        priority: 'High',
        status: 'In Progress',
        createdAt: '2024-12-25T09:15:00Z'
      },
      {
        id: 4,
        subject: 'Generator fuel system check',
        equipmentId: 4,
        type: 'Preventive',
        scheduledDate: '2025-01-02',
        duration: 1.5,
        assignedTechnicianId: 11,
        priority: 'Medium',
        status: 'New',
        createdAt: '2024-12-24T16:45:00Z'
      },
      {
        id: 5,
        subject: 'Software updates and cleanup',
        equipmentId: 5,
        type: 'Preventive',
        scheduledDate: '2025-01-05',
        duration: 1,
        assignedTechnicianId: 6,
        priority: 'Low',
        status: 'New',
        createdAt: '2024-12-27T11:20:00Z'
      },
      {
        id: 6,
        subject: 'Emergency hydraulic repair',
        equipmentId: 3,
        type: 'Corrective',
        scheduledDate: '2024-12-20',
        duration: 6,
        assignedTechnicianId: 1,
        priority: 'High',
        status: 'Repaired',
        createdAt: '2024-12-20T08:00:00Z'
      },
      {
        id: 7,
        subject: 'Hydraulic pressure adjustment',
        equipmentId: 3,
        type: 'Corrective',
        scheduledDate: '2024-12-15',
        duration: 2,
        assignedTechnicianId: 7,
        priority: 'High',
        status: 'Repaired',
        createdAt: '2024-12-15T13:30:00Z'
      },
      {
        id: 8,
        subject: 'Hydraulic seal replacement',
        equipmentId: 3,
        type: 'Corrective',
        scheduledDate: '2024-12-10',
        duration: 4,
        assignedTechnicianId: 10,
        priority: 'High',
        status: 'Repaired',
        createdAt: '2024-12-10T10:15:00Z'
      },
      {
        id: 9,
        subject: 'Conveyor belt alignment',
        equipmentId: 6,
        type: 'Preventive',
        scheduledDate: '2025-01-08',
        duration: 2,
        assignedTechnicianId: 7,
        priority: 'Low',
        status: 'New',
        createdAt: '2024-12-27T15:30:00Z'
      },
      {
        id: 10,
        subject: 'Chiller refrigerant leak',
        equipmentId: 7,
        type: 'Corrective',
        scheduledDate: '2024-12-29',
        duration: 5,
        assignedTechnicianId: 8,
        priority: 'High',
        status: 'New',
        createdAt: '2024-12-27T16:45:00Z'
      },
      {
        id: 11,
        subject: 'Network switch firmware update',
        equipmentId: 8,
        type: 'Preventive',
        scheduledDate: '2025-01-10',
        duration: 1,
        assignedTechnicianId: 9,
        priority: 'Low',
        status: 'New',
        createdAt: '2024-12-27T17:00:00Z'
      },
      {
        id: 12,
        subject: 'Welding robot calibration',
        equipmentId: 9,
        type: 'Preventive',
        scheduledDate: '2025-01-12',
        duration: 3,
        assignedTechnicianId: 8,
        priority: 'Medium',
        status: 'New',
        createdAt: '2024-12-27T18:15:00Z'
      },
      {
        id: 13,
        subject: 'UPS battery replacement',
        equipmentId: 10,
        type: 'Corrective',
        scheduledDate: '2024-12-30',
        duration: 4,
        assignedTechnicianId: 11,
        priority: 'High',
        status: 'In Progress',
        createdAt: '2024-12-26T09:30:00Z'
      },
      {
        id: 14,
        subject: 'AI system optimization',
        equipmentId: 2,
        type: 'Preventive',
        scheduledDate: '2025-01-15',
        duration: 2,
        assignedTechnicianId: 12,
        priority: 'Medium',
        status: 'New',
        createdAt: '2024-12-27T19:00:00Z'
      },
      {
        id: 15,
        subject: 'Cybersecurity audit',
        equipmentId: 8,
        type: 'Preventive',
        scheduledDate: '2025-01-20',
        duration: 3,
        assignedTechnicianId: 9,
        priority: 'High',
        status: 'New',
        createdAt: '2024-12-27T20:30:00Z'
      },
      {
        id: 16,
        subject: 'Injection molding temperature control',
        equipmentId: 11,
        type: 'Corrective',
        scheduledDate: '2024-12-31',
        duration: 3,
        assignedTechnicianId: 13,
        priority: 'Medium',
        status: 'New',
        createdAt: '2024-12-27T21:00:00Z'
      },
      {
        id: 17,
        subject: 'Air compressor pressure valve',
        equipmentId: 12,
        type: 'Corrective',
        scheduledDate: '2025-01-03',
        duration: 2,
        assignedTechnicianId: 14,
        priority: 'Medium',
        status: 'New',
        createdAt: '2024-12-27T21:30:00Z'
      },
      {
        id: 18,
        subject: 'Database backup verification',
        equipmentId: 13,
        type: 'Preventive',
        scheduledDate: '2025-01-07',
        duration: 1,
        assignedTechnicianId: 15,
        priority: 'Low',
        status: 'New',
        createdAt: '2024-12-27T22:00:00Z'
      },
      {
        id: 19,
        subject: 'Forklift hydraulic system service',
        equipmentId: 14,
        type: 'Preventive',
        scheduledDate: '2025-01-09',
        duration: 2.5,
        assignedTechnicianId: 13,
        priority: 'Low',
        status: 'New',
        createdAt: '2024-12-27T22:30:00Z'
      },
      {
        id: 20,
        subject: 'Transformer oil analysis',
        equipmentId: 15,
        type: 'Preventive',
        scheduledDate: '2025-01-11',
        duration: 1.5,
        assignedTechnicianId: 14,
        priority: 'High',
        status: 'New',
        createdAt: '2024-12-27T23:00:00Z'
      },
      {
        id: 21,
        subject: 'Firewall security update',
        equipmentId: 16,
        type: 'Preventive',
        scheduledDate: '2025-01-13',
        duration: 2,
        assignedTechnicianId: 18,
        priority: 'High',
        status: 'New',
        createdAt: '2024-12-27T23:30:00Z'
      },
      {
        id: 22,
        subject: 'Packaging machine sensor calibration',
        equipmentId: 17,
        type: 'Corrective',
        scheduledDate: '2025-01-04',
        duration: 2,
        assignedTechnicianId: 16,
        priority: 'Medium',
        status: 'New',
        createdAt: '2024-12-28T00:00:00Z'
      },
      {
        id: 23,
        subject: 'HVAC filter replacement',
        equipmentId: 18,
        type: 'Preventive',
        scheduledDate: '2025-01-06',
        duration: 1,
        assignedTechnicianId: 17,
        priority: 'Low',
        status: 'New',
        createdAt: '2024-12-28T00:30:00Z'
      }
    ]
  };

  // Store in localStorage
  localStorage.setItem('gearguard-data', JSON.stringify(demoData));
  return demoData;
};