import React from 'react';
import { X, QrCode, Download, Printer } from 'lucide-react';
import { QRCodeGenerator } from '../utils/smartFeatures';

const QRCodeModal = ({ equipment, onClose }) => {
  if (!equipment) return null;

  const qrData = QRCodeGenerator.generateEquipmentQR(equipment.id);

  const handleDownload = () => {
    const link = document.createElement('a');
    link.href = qrData.printableUrl;
    link.download = `${equipment.name}-QR.png`;
    link.click();
  };

  const handlePrint = () => {
    const printWindow = window.open('', '_blank');
    printWindow.document.write(`
      <html>
        <head>
          <title>QR Code - ${equipment.name}</title>
          <style>
            body { 
              font-family: Arial, sans-serif; 
              text-align: center; 
              padding: 20px; 
            }
            .qr-container { 
              border: 2px solid #000; 
              padding: 20px; 
              margin: 20px auto; 
              width: fit-content; 
            }
            .equipment-info { 
              margin-bottom: 20px; 
              font-size: 14px; 
            }
            .qr-code { 
              margin: 20px 0; 
            }
            .instructions { 
              font-size: 12px; 
              color: #666; 
              margin-top: 20px; 
            }
          </style>
        </head>
        <body>
          <div class="qr-container">
            <h2>${equipment.name}</h2>
            <div class="equipment-info">
              <p><strong>Serial:</strong> ${equipment.serialNumber}</p>
              <p><strong>Location:</strong> ${equipment.location}</p>
              <p><strong>Department:</strong> ${equipment.department}</p>
            </div>
            <div class="qr-code">
              <img src="${qrData.printableUrl}" alt="QR Code" />
            </div>
            <div class="instructions">
              <p>Scan this QR code to access equipment details and create maintenance requests</p>
              <p>Generated by GearGuard Maintenance System</p>
            </div>
          </div>
        </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.print();
  };

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
      <div className="bg-white rounded-lg p-6 w-full max-w-md">
        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center">
            <QrCode className="h-6 w-6 text-blue-600 mr-2" />
            <h2 className="text-xl font-semibold">Equipment QR Code</h2>
          </div>
          <button
            onClick={onClose}
            className="text-gray-400 hover:text-gray-600"
          >
            <X className="h-6 w-6" />
          </button>
        </div>

        {/* Equipment Info */}
        <div className="mb-6 p-4 bg-gray-50 rounded-lg">
          <h3 className="font-medium text-gray-900 mb-2">{equipment.name}</h3>
          <div className="text-sm text-gray-600 space-y-1">
            <p><span className="font-medium">Serial:</span> {equipment.serialNumber}</p>
            <p><span className="font-medium">Location:</span> {equipment.location}</p>
            <p><span className="font-medium">Department:</span> {equipment.department}</p>
          </div>
        </div>

        {/* QR Code */}
        <div className="text-center mb-6">
          <div className="inline-block p-4 bg-white border-2 border-gray-300 rounded-lg">
            <img 
              src={qrData.url} 
              alt="Equipment QR Code"
              className="w-48 h-48"
            />
          </div>
        </div>

        {/* Instructions */}
        <div className="mb-6 p-4 bg-blue-50 rounded-lg">
          <h4 className="font-medium text-blue-900 mb-2">How to use:</h4>
          <ul className="text-sm text-blue-800 space-y-1">
            <li>• Print and attach to equipment</li>
            <li>• Scan to view equipment details</li>
            <li>• Quick access to maintenance history</li>
            <li>• Create breakdown requests instantly</li>
          </ul>
        </div>

        {/* Action Buttons */}
        <div className="flex gap-3">
          <button
            onClick={handleDownload}
            className="flex-1 bg-blue-600 text-white py-2 px-4 rounded-lg hover:bg-blue-700 flex items-center justify-center gap-2"
          >
            <Download className="h-4 w-4" />
            Download
          </button>
          <button
            onClick={handlePrint}
            className="flex-1 bg-gray-600 text-white py-2 px-4 rounded-lg hover:bg-gray-700 flex items-center justify-center gap-2"
          >
            <Printer className="h-4 w-4" />
            Print
          </button>
        </div>

        {/* QR Data Info */}
        <div className="mt-4 p-3 bg-gray-100 rounded text-xs text-gray-600">
          <p className="font-medium mb-1">QR Code Data:</p>
          <p className="break-all">{qrData.data}</p>
        </div>
      </div>
    </div>
  );
};

export default QRCodeModal;